### ISSUE TITLE
Bad Request from imgjsonpserver

### ISSUE THREAD

**Issue by amoHoban** [plyfe/ember-aviary#4]
Hi, thanks for this great addon but unfortunately i couldnt make it work with a url. Most ember apps are used as a client to some (rest) api, mostly not on the same domain. Hence the usecase for "url" would be very common. Unfortunately im getting back a "400 Bad Request" when the component does following call:

http://featherservices.aviary.com/imgjsonpserver.aspx?callback=jQuery17105475396194960922_1427989630111&url=http...

I guess it informs the servers about the url and tries to invoke a callback.

**Comment by mfamilia** [comment]
Hey @amoHoban, can you provide steps to reproduce this?

Please check out the demo provided [here](https://github.com/danielleadams/ember-aviary-demo) for supported usage.

**Comment by amoHoban** [comment]
The issue is gone. Maybe temporary. Thanks!
