### ISSUE TITLE
image is resized

### ISSUE THREAD

**Issue by amoHoban** [plyfe/ember-aviary#6]
Too bad, my 2560x1600 image was resized to 800x650 after just flipping it horizontally. Is that always the case? Can this be changed to keep the resolution at least to HD?

**Comment by danielleadams** [comment]
Aviary is meant to handle file sizes intended for web display, not original resolutions (per their <a href="https://developers.aviary.com/docs/web/setup-guide">docs</a>). The default maximum width and height is 800px, as recommended by Aviary. In future versions of Ember Aviary, we can make this customizable, but this would just be to make it smaller.

**Comment by ksin** [comment]
@amoHoban You're welcome to make a pull request for any of the options supported by the Aviary SDK. :)

**Comment by amoHoban** [comment]
Thank you!

ok will look into that. I am in contact with aviary team regarding higher res images. It seems to be possible with additional parameters and setup steps, but requires approval. I will create a fork as soon as I know more.

**Comment by danielleadams** [comment]
Sounds good. Thanks, @amoHoban!
